name: Go
on: [push]
jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - uses: actions/checkout@v2

    - run: |
        go test -coverprofile=coverage.txt ./...
        go run github.com/ysmood/got/cmd/check-cov

