name: Go
on: [push]
jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: actions/checkout@v2

    - run: |
        go get github.com/ysmood/golangci-lint
        golangci-lint
        go test -coverprofile=coverage.txt
        go get github.com/ysmood/got/cmd/check-cov
        check-cov

  windows:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: actions/checkout@v2

    - run: go test